### ISSUE TITLE
small bug that gives compilation error?

### ISSUE THREAD

**Issue by nakasan617** [SRI-CSL/clam-prov#8]
I have been remaking clam-prov but I faced this compilation error several times, so thought about posting it.
What you need to do is literally change -> into . and all the issue will be resolved.

![Screenshot from 2021-09-23 15-22-46](https://user-images.githubusercontent.com/44285097/134578689-1ea38b1d-9a98-4585-98cf-8739f6621fb5.png)

**Comment by caballa** [comment]
Fixed. Sorry about that.
