### ISSUE TITLE
new version issue?

### ISSUE THREAD

**Issue by nakasan617** [SRI-CSL/clam-prov#9]
I have been getting this error as I am trying to create dotfiles after devirtualizing the bitcode whose executable was first created with libc.a from musllvm.
This happened with several executions I had so I think it is an issue with the code, it seems to be segfaulting in seadsa and the environment is in vagrant in clam-prov repo.
I have created a executable 
`wllvm sourcecode.c libc.a -Wall -o executable`
then extracted the bitcode with 
`extract-bc -b executable`
then I used the clam-pp and this happened
![clamfail](https://user-images.githubusercontent.com/44285097/134622332-78526490-6e7c-484f-a739-8492bb06f65a.PNG)

**Comment by nakasan617** [comment]
I confirmed with the older version (I checked with the commit on June 21st) worked fine, so I think this is an issue that's newly created with the newer version

**Comment by caballa** [comment]
can you give me some the code and command so that I can reproduce it?

**Comment by nakasan617** [comment]
Hi sorry for the late response, I tried and I could not for now so I will close the issue temporarily. I will make the same environment again and see what happens, if it shows up again, I will reopen.
